### ISSUE TITLE
速度咋样啊，大佬？

### ISSUE THREAD

**Issue by hyaihjq** [hpc203/YOLObile-opencv-dnn#1]

**Comment by hpc203** [comment]
在win10-cpu机器上，跑一张图片耗时191.62毫秒

**Comment by 1343464520** [comment]
这个怎么跟原模型差不多大呀，我在gpu模式下,测试速度跟yolov3差不多额，，我是直接用的你的cfg文件，输入用的416x416，是不是哪里操作有问题呢@hpc203

**Comment by hpc203** [comment]
> 这个怎么跟原模型差不多大呀，我在gpu模式下,测试速度跟yolov3差不多额，，我是直接用的你的cfg文件，输入用的416x416，是不是哪里操作有问题呢@hpc203

我测试的时候输入图片是320x320的，416x416这种我曾经试过的，在bug.jpg图片上效果不行的，我就改成320x320的

**Comment by 1343464520** [comment]
> > 这个怎么跟原模型差不多大呀，我在gpu模式下,测试速度跟yolov3差不多额，，我是直接用的你的cfg文件，输入用的416x416，是不是哪里操作有问题呢@hpc203
> 
> 我测试的时候输入图片是320x320的，416x416这种我曾经试过的，在bug.jpg图片上效果不行的，我就改成320x320的

为啥尺寸大效果反而不好呢，416x416速度怎样？还有您训练和测试都用的320x320吗？我现在用的darknet自带测试模式下(开GPU模式)，相比yolov3平均帧数只快1fps，yolov3(416)为40.1FPS, yolobile(416)为41.5FPS，不知道为啥

**Comment by hpc203** [comment]
> > > 这个怎么跟原模型差不多大呀，我在gpu模式下,测试速度跟yolov3差不多额，，我是直接用的你的cfg文件，输入用的416x416，是不是哪里操作有问题呢@hpc203
> > 
> > 
> > 我测试的时候输入图片是320x320的，416x416这种我曾经试过的，在bug.jpg图片上效果不行的，我就改成320x320的
> 
> 为啥尺寸大效果反而不好呢，416x416速度怎样？还有您训练和测试都用的320x320吗？我现在用的darknet自带测试模式下(开GPU模式)，相比yolov3平均帧数只快1fps，yolov3(416)为40.1FPS, yolobile(416)为41.5FPS，不知道为啥

我这个程序只做前向推理，训练的问题得要去问YOLObile的作者。我这里的工作是把他训练出来的.pt文件转换成.weights文件，然后用Opencv的dnn模块做前向推理的目标检测，从而彻底摆脱对深度学习框架的依赖，做到极简主义

**Comment by MuhammadAsadJaved** [comment]
@1343464520 嗨，您如何测试YOLObile？ 您使用哪个项目测试速度？

**Comment by runauto** [comment]
训练速度太慢了，感觉没有作者宣传的那么好。
